---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role edx-notes-api
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

# - name: setup the env file
#   template: >
#     src="edx/app/insights/insights_env.j2"
#     dest="{{ insights_app_dir }}/insights_env"
#     owner={{ insights_user }}
#     group={{ insights_user }}
#     mode=0644

- name: checkout code
  git: >
    dest={{ edx_notes_api_code_dir }} repo={{ edx_notes_api_source_repo }} version={{ EDX_NOTES_API_VERSION }}
    accept_hostkey=yes key_file="{{ edx_notes_api_home }}/.ssh/id_rsa"
  register: edx_notes_api_code_checkout
  #sudo_user: "{{ edx_notes_api_role_name }}"
  sudo_user: "edx-notes-api"

- name: install application requirements
  pip: >
    requirements="{{ edx_notes_api_requirements_base }}/{{ item }}"
    virtualenv="{{ edx_notes_api_venv_dir }}" state=present
    extra_args="--exists-action w"
  sudo_user: "{{ edx_notes_api_user }}"
  with_items: edx_notes_api_requirements

# - name: migrate
#   shell: >
#     chdir={{ insights_code_dir }}
#     DB_MIGRATION_USER={{ COMMON_MYSQL_MIGRATE_USER }}
#     DB_MIGRATION_PASS={{ COMMON_MYSQL_MIGRATE_PASS }}
#     {{ insights_venv_bin }}/python {{ insights_manage }} migrate --noinput
#   sudo_user: "{{ insights_user }}"
#   environment: "{{ insights_environment }}"
#   when: migrate_db is defined and migrate_db|lower == "yes"

# - name: write out the supervisior wrapper
#   template: >
#     src=edx/app/insights/insights.sh.j2
#     dest={{ insights_app_dir }}/{{ insights_service_name }}.sh
#     mode=0650 owner={{ supervisor_user }} group={{ common_web_user }}
#   notify: restart insights

# - name: write supervisord config
#   template: >
#     src=edx/app/supervisor/conf.d.available/insights.conf.j2
#     dest="{{ supervisor_available_dir }}/{{ insights_service_name }}.conf"
#     owner={{ supervisor_user }} group={{ common_web_user }} mode=0644
#   notify: restart insights

# - name: enable supervisor script
#   file: >
#     src={{ supervisor_available_dir }}/{{ insights_service_name }}.conf
#     dest={{ supervisor_cfg_dir }}/{{ insights_service_name }}.conf
#     state=link
#     force=yes
#   notify: restart insights
#   when: not disable_edx_services

# - name: update supervisor configuration
#   shell: "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
#   when: not disable_edx_services

# - name: create symlinks from the venv bin dir
#   file: >
#     src="{{ insights_venv_bin }}/{{ item }}"
#     dest="{{ COMMON_BIN_DIR }}/{{ item.split('.')[0] }}.{{ insights_role_name }}"
#     state=link
#   with_items:
#   - python
#   - pip
#   - django-admin.py

# - name: create manage.py symlink
#   file: >
#     src="{{ insights_manage }}"
#     dest="{{ COMMON_BIN_DIR }}/manage.{{ insights_role_name }}"
#     state=link

# - include: tag_ec2.yml tags=deploy
#   when: COMMON_TAG_EC2_INSTANCE
